### ISSUE TITLE
Question about objective function to optimize?

### ISSUE THREAD

**Issue by SubChange** [bjorntsv/pyfemu#1]
Firstly, thank you very much to your work, which has bring many conveniences to my problem.

These days, I have read your codes line by line, I found that the objective function seems only contains fraquency discrepancies. See code as the follow:

```python
# Evaluate the objective function for the initial analysis
J_star = np.sum(np.diag(W)*((lamda_m - lamda[0, :])/lamda[0, :])**2)
J_star_list.append(J_star)
```

> The variable `lamda_m` is the measured frequencies, and the variable `lamda[0,:]` is the initial numerical frequencies. The objective function only sums the discrepancies of the aboved two variables.

However, in many studies about finite element updating, the objective function generally contains a frequency term and modal shape term as the follow:

$$
\sum\limits^n_{i=1}{(\frac{\lambda_i^{EXP}-\lambda_i(\alpha)}{\lambda_i^{EXP}}\cdot w_{\lambda_i})^2+||Q_i{(\Psi_i^{EXP,m}-\Psi^m_i(\alpha)})\cdot w_{\Psi_i}||^2_2}
$$

I want to know does the reference [1] only considers frequency term? Meanwhile, If I want to add the modal shape discrepancy term, how can I do? Could you please give me some suggections. Thank you very much.

**Reference**
[1] B. T. Svendsen, Ø. W. Petersen, G. T. Frøseth, and A. Rønnquist, “Improved finite element model updating of a full-scale steel bridge using sensitivity analysis,” Struct. Infrastruct. Eng., pp. 1–17, Jul. 2021, doi: https://doi.org/10.1080/15732479.2021.1944227.

**Comment by bjorntsv** [comment]
Hi,

Thanks for taking interest in the PYFEMU work!

The PYFEMU code for the simple numerical case study does not include updating on MAC values, only on frequencies. The main reason is that the “measured” mode shapes (representing the mode shapes obtained from the simulated measurements) and the numerical mode shapes are very similar for this particular case study. In this case study, the implementation of the framework is more efficient without the implementation of the MAC values. 

The explanation of the implementation using MAC values is provided in Section 2.1 of the paper (“_Improved finite element model updating of a full-scale steel bridge using sensitivity analysis_”) and is straightforward. The paper is open access and can easily be accessed [here](https://www.tandfonline.com/doi/full/10.1080/15732479.2021.1944227). You can also check out my [Researchgate profile](https://www.researchgate.net/publication/354380166_FE_model_updating_in_Python) where a more detailed description of this numerical case study and the framework is included.

I hope this answers your question! Feel free to open this issue again if you have further questions.
